import { BossId } from '../../types';
import { GalleryEntry } from '../base';
import { SpriteKey } from '../sprites/base';

export const GALLERY_BOSSES: Record<BossId, GalleryEntry> = {
  [BossId.GUARDIAN]: {
    id: BossId.GUARDIAN,
    name: 'Guardian',
    chineseName: '赛博守护者',
    description: '赛博空间的初级守护程序,以优雅的正弦轨迹游弋于霓虹战场,全向弹幕系统是对新手飞行员的第一道试炼。',
    rarity: 'common',
    unlock: 'level',
    unlockParam: 1,
    sprite: SpriteKey.BOSS_GUARDIAN,
    color: '#4488ff',
  },
  [BossId.INTERCEPTOR]: {
    id: BossId.INTERCEPTOR,
    name: 'Interceptor',
    chineseName: '疾风拦截者',
    description: '突击型战斗平台,以之字形轨迹高速机动,双模式火力系统兼顾区域封锁与精准打击,是速度与火力的完美结合。',
    rarity: 'common',
    unlock: 'level',
    unlockParam: 2,
    sprite: SpriteKey.BOSS_INTERCEPTOR,
    color: '#ff4488',
  },
  [BossId.DESTROYER]: {
    id: BossId.DESTROYER,
    name: 'Destroyer',
    chineseName: '装甲毁灭者',
    description: '重型装甲作战单元,以八字轨迹碾压战场,三重进化形态层层解锁毁灭之力,每个阶段都更加致命。',
    rarity: 'rare',
    unlock: 'level',
    unlockParam: 3,
    sprite: SpriteKey.BOSS_DESTROYER,
    color: '#44ff88',
  },
  [BossId.ANNIHILATOR]: {
    id: BossId.ANNIHILATOR, 
    name: 'Annihilator',
    chineseName: '幽灵歼灭者',
    description: '装备光学迷彩的幽灵战斗机,空间跃迁轨迹如鬼魅般难以捉摸,全方位弹雨与锁定追踪的双重威胁令人防不胜防。',
    rarity: 'rare',
    unlock: 'level',
    unlockParam: 4,
    sprite: SpriteKey.BOSS_ANNIHILATOR,
    color: '#ff8844',
  },
  [BossId.DOMINATOR]: {
    id: BossId.DOMINATOR,
    name: 'Dominator',
    chineseName: '弹幕主宰者',
    description: '高能粒子壁垒,沿螺旋轨道释放无尽弹幕洪流,致密火力网封锁一切突破可能,是弹幕艺术的极致体现。',
    rarity: 'epic',
    unlock: 'level',
    unlockParam: 5,
    sprite: SpriteKey.BOSS_DOMINATOR,
    color: '#8844ff',
  },
  [BossId.OVERLORD]: {
    id: BossId.OVERLORD,
    name: 'Overlord',
    chineseName: '战场霸主',
    description: '双体协同战舰,智能追踪锁定目标,融合扩散弹幕、制导武器与连续激光的复合火力系统,是战场的绝对统治者。',
    rarity: 'epic',
    unlock: 'level',
    unlockParam: 6,
    sprite: SpriteKey.BOSS_OVERLORD,
    color: '#ff44ff',
  },
  [BossId.TITAN]: {
    id: BossId.TITAN,
    name: 'Titan',
    chineseName: '泰坦要塞',
    description: '三角构型的空中要塞,缓慢降临碾压战场,三阶觉醒形态逐步释放激光风暴与制导毁灭,每次觉醒都是噩梦的升级。',
    rarity: 'legendary',
    unlock: 'level',
    unlockParam: 7,
    sprite: SpriteKey.BOSS_TITAN,
    color: '#44ff44',
  },
  [BossId.COLOSSUS]: {
    id: BossId.COLOSSUS,
    name: 'Colossus',
    chineseName: '钢铁巨像',
    description: '八足钢铁巨蛛,激进突进撕裂战线,多重武装系统配合激光护卫机提供防空掩护,是移动的死亡堡垒。',
    rarity: 'legendary',
    unlock: 'level',
    unlockParam: 8,
    sprite: SpriteKey.BOSS_COLOSSUS,
    color: '#ffff44',
  },
  [BossId.LEVIATHAN]: {
    id: BossId.LEVIATHAN,
    name: 'Leviathan',
    chineseName: '深渊利维坦',
    description: '环状中枢战体,以极限机动穿梭战场,五重武器矩阵配合双护卫机编队协防,构筑无法逃脱的死亡领域。',
    rarity: 'mythic',
    unlock: 'level',
    unlockParam: 9,
    sprite: SpriteKey.BOSS_LEVIATHAN,
    color: '#44ffff',
  },
  [BossId.APOCALYPSE]: {
    id: BossId.APOCALYPSE,
    name: 'Apocalypse',
    chineseName: '天启审判',
    description: '终极龙王,轨迹莫测难寻,五维火力全域覆盖,双布雷机僚机协同,四重超载形态逐次显现,是霓虹战场的终极审判。',
    rarity: 'mythic',
    unlock: 'level',
    unlockParam: 10,
    sprite: SpriteKey.BOSS_APOCALYPSE,
    color: '#ff0000',
  },
};
