import { EnemyId } from "../../types";
import { GalleryEntry } from '../base';
import { SpriteKey } from '../sprites/base';

export const GALLERY_ENEMIES: Record<EnemyId, GalleryEntry> = {
  [EnemyId.NORMAL]: {
    id: EnemyId.NORMAL,
    name: 'Scout',
    chineseName: '侦察机',
    description: '敌军基础侦察单位,轻装甲低速度,是战场上最常见的炮灰,也是积累分数的主要来源。',
    rarity: 'common',
    unlock: 'default',
    unlockParam: 0,
    sprite: SpriteKey.ENEMY_NORMAL,
    color: '#ff4444',
  },
  [EnemyId.FAST]: {
    id: EnemyId.FAST,
    name: 'Wing',
    chineseName: '疾风飞翼',
    description: '高速飞翼战机,以折线轨迹高速机动难以锁定,虽然装甲薄弱但射速惊人,是灵活而危险的对手。',
    rarity: 'common',
    unlock: 'level',
    unlockParam: 1,
    sprite: SpriteKey.ENEMY_FAST,
    color: '#aa44ff',
  },
  [EnemyId.TANK]: {
    id: EnemyId.TANK,
    name: 'Tank',
    chineseName: '重装坦克',
    description: '搭载纳米复合装甲的移动堡垒,吸收80%常规武器伤害,虽然移动缓慢但配备矢量推进系统可短距冲刺,需要集火才能快速摧毁。',
    rarity: 'common',
    unlock: 'level',
    unlockParam: 1,
    sprite: SpriteKey.ENEMY_TANK,
    color: '#44ff44',
  },
  [EnemyId.KAMIKAZE]: {
    id: EnemyId.KAMIKAZE,
    name: 'Kamikaze',
    chineseName: '自杀尖刺',
    description: '装备量子斥力场的高速突击单位,接近时瞬间加速至亚光速,机身覆盖超硬合金刺状结构,血量极低但速度极快,以冲撞造成致命伤害。',
    rarity: 'uncommon',
    unlock: 'level',
    unlockParam: 2,
    sprite: SpriteKey.ENEMY_KAMIKAZE,
    color: '#ffaa44',
  },
  [EnemyId.ELITE_GUNBOAT]: {
    id: EnemyId.ELITE_GUNBOAT,
    name: 'Gunboat',
    chineseName: '精英炮艇',
    description: '星核驱动的精英级重型炮艇,血量火力机动性全面超越常规单位,同时锁定多目标发射能量聚合光束,核心反应堆护盾抵御90%常规攻击,是敌方舰队的终极杀器。',
    rarity: 'rare',
    unlock: 'level',
    unlockParam: 3,
    sprite: SpriteKey.ENEMY_GUNBOAT,
    color: '#4444ff',
  },
  [EnemyId.LASER_INTERCEPTOR]: {
    id: EnemyId.LASER_INTERCEPTOR,
    name: 'Interceptor',
    chineseName: '光束拦截机',
    description: '装备相位锁定光束炮的双翼拦截机,在战场中段悬停蓄力后发射切割空间的强大激光束,对直线上所有目标造成毁灭性打击。',
    rarity: 'rare',
    unlock: 'level',
    unlockParam: 4,
    sprite: SpriteKey.ENEMY_INTERCEPTOR,
    color: '#44ffff',
  },
  [EnemyId.MINE_LAYER]: {
    id: EnemyId.MINE_LAYER,
    name: 'Mine Layer',
    chineseName: '战术布雷机',
    description: '配备量子感应地雷部署系统的战术单位,缓慢移动但持续留下隐形空雷,根据能量特征自动触发,形成致命的防御网络。',
    rarity: 'rare',
    unlock: 'level',
    unlockParam: 4,
    sprite: SpriteKey.ENEMY_LAYER,
    color: '#aaaa44',
  },
  [EnemyId.PULSAR]: {
    id: EnemyId.PULSAR,
    name: 'Pulsar',
    chineseName: '脉冲战机',
    description: '轻量化合金机身的高速战机,配备高频脉冲武器系统在短时间内倾泻大量弹药,虽然装甲薄弱但依靠高机动性规避火力。',
    rarity: 'uncommon',
    unlock: 'level',
    unlockParam: 2,
    sprite: SpriteKey.ENEMY_PULSAR,
    color: '#ff44ff',
  },
  [EnemyId.FORTRESS]: {
    id: EnemyId.FORTRESS,
    name: 'Fortress',
    chineseName: '空中堡垒',
    description: '搭载多层能量护盾和复合装甲的重装单位,移动缓慢但火力巨大,多管火炮系统覆盖广阔战场,是敌方舰队的核心火力输出。',
    rarity: 'epic',
    unlock: 'level',
    unlockParam: 5,
    sprite: SpriteKey.ENEMY_FORTRESS,
    color: '#666666',
  },
  [EnemyId.STALKER]: {
    id: EnemyId.STALKER,
    name: 'Stalker',
    chineseName: '猎杀追踪机',
    description: '装备量子纠缠锁定系统的精英猎杀单位,动作灵活爆发伤害高,预判移动轨迹发射的追踪弹几乎无法被常规手段规避。',
    rarity: 'uncommon',
    unlock: 'level',
    unlockParam: 3,
    sprite: SpriteKey.ENEMY_STALKER,
    color: '#ff8844',
  },
  [EnemyId.BARRAGE]: {
    id: EnemyId.BARRAGE,
    name: 'Barrage',
    chineseName: '弹幕压制机',
    description: '搭载多管螺旋弹幕系统的战术压制单位,制造覆盖面极广的弹幕,螺旋能量弹形成复杂弹道网络,迫使玩家在极小安全区域内机动。',
    rarity: 'rare',
    unlock: 'level',
    unlockParam: 4,
    sprite: SpriteKey.ENEMY_BARRAGE,
    color: '#8844ff',
  },
};
