import { WeaponId } from '../../types';
import { GalleryEntry } from '../base';
import { SpriteKey } from '../sprites/base';

export const GALLERY_WEAPONS: Record<WeaponId, GalleryEntry> = {
    [WeaponId.VULCAN]: {
        id: WeaponId.VULCAN,
        name: 'Vulcan Gun',
        chineseName: '星裂火神炮',
        description: '智能弹道预测系统根据敌机密度自动调整扇形覆盖，纳米级表面处理确保远距离精准打击。',
        rarity: 'common',
        unlock: 'default',
        unlockParam: 0,
        sprite: SpriteKey.BULLET_VULCAN,
        color: '#ebdd17ff',
    },
    [WeaponId.LASER]: {
        id: WeaponId.LASER,
        name: 'Laser Cannon',
        chineseName: '裂空镭射炮',
        description: '量子纠缠技术聚焦的高能光束，无视护盾直接穿透目标核心。',
        rarity: 'rare',
        unlock: 'level',
        unlockParam: 5,
        sprite: SpriteKey.BULLET_LASER,
        color: '#3fc4f0ff',
    },
    [WeaponId.PLASMA]: {
        id: WeaponId.PLASMA,
        name: 'Plasma Cannon',
        chineseName: '等离子炮',
        description: '反物质约束场封装超高温等离子体，命中后形成微型奇点。',
        rarity: 'epic',
        unlock: 'achievement',
        unlockParam: 10001,
        sprite: SpriteKey.BULLET_PLASMA,
        color: '#ed64a6',
    },
    [WeaponId.MISSILE]: {
        id: WeaponId.MISSILE,
        name: 'Homing Missile',
        chineseName: '幽灵追踪导弹',
        description: '搭载第五代AI导航系统的智能导弹，通过量子雷达锁定目标生命信号，可进行多次空间折跃追击。',
        rarity: 'rare',
        unlock: 'level',
        unlockParam: 3,
        sprite: SpriteKey.BULLET_MISSILE,
        color: '#ec6f73',
    },
    [WeaponId.WAVE]: {
        id: WeaponId.WAVE,
        name: 'Wave Cannon',
        chineseName: '相位海啸炮',
        description: '通过大量共振水晶同步激发的宽频能量波，形成覆盖大范围扇区的相位潮汐。',
        rarity: 'epic',
        unlock: 'level',
        unlockParam: 7,
        sprite: SpriteKey.BULLET_WAVE,
        color: '#1e8de7ff',
    },
    [WeaponId.TESLA]: {
        id: WeaponId.TESLA,
        name: 'Tesla Cannon',
        chineseName: '特斯拉链式闪电',
        description: '释放超高压电弧武器，通过离子化空气在敌群间形成连锁传导。',
        rarity: 'legendary',
        unlock: 'achievement',
        unlockParam: 20001,
        sprite: SpriteKey.BULLET_TESLA,
        color: '#1053d9ff',
    },
    [WeaponId.MAGMA]: {
        id: WeaponId.MAGMA,
        name: 'Magma Cannon',
        chineseName: '恒星熔岩弹',
        description: '封装恒星核心物质的超高温武器，命中后形成持续灼烧的熔岩区域。',
        rarity: 'epic',
        unlock: 'level',
        unlockParam: 8,
        sprite: SpriteKey.BULLET_MAGMA,
        color: '#f60',
    },
    [WeaponId.SHURIKEN]: {
        id: WeaponId.SHURIKEN,
        name: 'Shuriken',
        chineseName: '量子回旋刃',
        description: '采用单分子锋刃技术的回旋武器，边缘锋利度达原子级。',
        rarity: 'rare',
        unlock: 'level',
        unlockParam: 6,
        sprite: SpriteKey.BULLET_SHURIKEN,
        color: '#ccccccff',
    },
};